docs: network changes
opengovsg/im8-cfa-sandbox pull request #4
Opened 2022-05-19 09:03 UTC by hunter

This change includes some larger changes to network security:

* Block Internet access by default (with whitelisting)
* Account based environments
* Changed subnets to segments
* Basic guideline on microsegmentation
* Favour VPC Endpoints over VPC Peering and TGW

Thoughts?

2022-05-19 11:27 UTC, liangyuanruo commented on networking.md
> +Segregation of cloud resources **must** be achieved between environments (staging, UAT, production, etc), via separate accounts.
I am wondering if it is strictly necessary to _mandate_ complete segregation of cloud accounts for environments, over an alternative such as having separate VPCs? I'll admit that there are probably some security benefits from this as a default practice - such as simplifying the writing of IAM policies. If so perhaps we could expand this to include the justification.

2022-05-19 11:34 UTC, liangyuanruo commented on networking.md
> +Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to minimise pivot risk.
May I ask what does "pivot risk" mean?

2022-05-19 11:47 UTC, liangyuanruo commented on networking.md
> +Where available, VPC private endpoints should be used for cross-service communication (including 3rd-party service providers) to avoid having traffic crossing the open internet. For cases that don't
Good suggestion - I was not aware of VPC PrivateLink on AWS, but it appears to be a superior solution compared to VPC Peering because it constrains traffic to allowed endpoints.

2022-05-19 11:50 UTC, liangyuanruo commented
Thanks, @hunter, I posed a couple of questions but am generally supportive.

2022-05-19 11:52 UTC, liangyuanruo commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
Is this guideline for incoming traffic only? My understanding is that an app server deployed to a private subnet with a NAT Gateway is able to initiate connections to any external endpoint.

2022-05-19 12:14 UTC, ronghwa80 commented on networking.md
> +Segregation of cloud resources **must** be achieved between environments (staging, UAT, production, etc), via separate accounts.
https://docs.aws.amazon.com/whitepapers/latest/organizing-your-aws-environment/benefits-of-using-multiple-aws-accounts.html

By applying different account for different environment helps to limit the scope of impact from adverse events. This aligns with the assume breach mindset. :)

An AWS account provides security, access, and billing boundaries for your AWS resources that can help you achieve resource independence and isolation. This isolation boundary provides you with a way to limit the risks of an application-related issue, misconfiguration, or malicious actions. If an issue occurs within one account, impacts to workloads contained in other accounts can be either reduced or eliminated.

2022-05-19 12:16 UTC, ronghwa80 commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
This is more of referring to accessing the Internet through outgoing Internet traffic. Maybe we can sharpen this articulation. By blocking outgoing traffic by default, it can mitigate against exploitation of two stage vulnerabilities like Log4J.

2022-05-19 12:26 UTC, liangyuanruo approved these changes

2022-05-19 13:59 UTC, hunter commented on networking.md
> +Segregation of cloud resources **must** be achieved between environments (staging, UAT, production, etc), via separate accounts.
My initial edit of that line had a split between prod and non-prod. Production is usually the most critical for isolation with the remaining environments less so and could be combined. I felt the wording may end up with too many questions so opted to keep it simple but with a wider scope.

Although not a obvious security benefit, using account based environments means that quotas are not combined in the single account case, which could lead to denial of service (AWS API limits hit, unable to autoscale a resource, etc). Operationally, it also can have benefits for applying different AWS support tiers to different accounts.

2022-05-19 14:02 UTC, hunter commented on networking.md
> +Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to minimise pivot risk.
In this case, an app server could be compromised and an attack launched from that server to other servers in the autoscaling group (or anything else accessible in the segment).

2022-05-19 14:03 UTC, liangyuanruo commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
I am wondering how to achieve this in a way that is not overly onerous to the system. The default way is probably to modify the assigned security group of the app server to include the outgoing connection's target IPs, but this would obstruct API integration with external SaaS providers that do not commit to providing static IPs for integration against.

2022-05-19 14:12 UTC, hunter commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
My mistake on the unclear wording. What do we think of this change?

```suggestion
Outgoing Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
```

2022-05-19 15:08 UTC, liangyuanruo commented on networking.md
> +Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to minimise pivot risk.
I see, I am unsure as to whether this is a common term but I don't want to be pedantic 😅

2022-05-19 15:23 UTC, liangyuanruo commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
May I check what are the concrete steps that one may take to achieve domain whitelisting?

I am worried that this is non-trivial to achieve; and end up impose significant overheads on what could have been relatively straightforward SaaS integration.

2022-05-20 01:13 UTC, hunter commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
It used to be sticking a forward proxy (running squid or similar in a VM) was the only option in policy.

It doesn't have to follow as we develop new policy. It could be as basic as a default deny Security Group with destination IPs whitelisted.

For more advanced cases, an AWS network firewall running like a forward proxy can be utilised to cover more granular URL based filtering (as well as network inspection). It is more complex but not too difficult to automate (unlike Squid based solution). At scale, it also has the benefit of becoming a shared service for all accounts in an org to use as central egress and NAT (on the roadmap for GCC)

2022-05-20 01:19 UTC, hunter commented on networking.md
> +Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to minimise pivot risk.
It is a common term. Alternatively, "Lateral movement" might be another option (and perhaps better as less specific to a technique). @ronghwa80, any preference?

2022-05-20 01:56 UTC, ronghwa80 commented on networking.md
> +Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to minimise pivot risk.
@hunter, yes, I was thinking that you might be referring to lateral movement, which is a more generic term.

Agree with you that identity-based security in conjunction with network segmentation would form the fundamental of GTbA to limit the blast radius significantly. That said, I want to highlight that I agree with your approach of listing IAM roles as an example. It is good to provide some flexibility on how identity can be implemented, e.g. for certain implementation, the use of secret management tools like AWS secret manager will work as effectively.

2022-05-20 02:14 UTC, ronghwa80 commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
Thanks @liangyuanruo and @hunter.

This requirement is to solve insecure AWS default where the tradeoff inclines towards operation convenience. Yes, there is limitation on Security Groups and NACL w.r.t. domains whitelisting. Agree that this may impose some issues when applications integrate with SaaS that does not have fixed IP address range. 

On this, CSG with inputs from CODEX, GDS, and AWS colleagues have co-developed an IAC that has incorporated implementation of AWS network firewall to achieve this. This template is currently hosted on SHIP-HATS which I can share for more inputs. This template is currently scheduled for VAPT as we also intend to share publicly with WOG to help expedite Agencies' deployment.

Alternatively, if we were to take some risk, the whitelisting can be performed at IP address ranges that the SaaS uses. Then good to have this risk documented as part of standard process for informed decision.

2022-05-20 02:36 UTC, liangyuanruo commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
I see. Is it a reasonable expectation for a dev team to have to find out all the domain and IP addresses that a SaaS provider uses though, especially if the information may not have been published?

As a concrete example, FormSG uses Twilio for SMSes and DataDog for logging. These services provide an SDK for easy integration, but (afaik) their documentation do not provide any information about the specific domains or IPs that the SDK will be calling. Even if it were figured out, this may also be subject to unannounced change as the SDKs get upgraded or if the SaaS providers make infrastructural changes.

The only exceptions I can tell are for webhook callbacks, where an authentication scheme is usually communicated (signed headers, maybe fixed IPs), but these are connections initiated externally.

2022-05-20 02:42 UTC, liangyuanruo commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
Thanks @ronghwa80 for weighing in - seems that it may be premature to mandate this? Perhaps we should reduce the requirement to "recommend" instead?

2022-05-20 06:07 UTC, hunter commented on networking.md
> +Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to minimise pivot risk.
```suggestion
Individual resources in a segment should be further isolated from others by identity and network based controls (e.g. IAM roles, Security Groups, etc) to limit lateral movement. 
```

2022-05-20 06:54 UTC, liangyuanruo commented
> Thoughts on how to cover a pure/partial cloud-native application?

This is a great point @hunter; I think we are doing ourselves a great disservice if we cannot make this work, not just for DynamoDB and Lambda but also for other CSP services such as Firebase, Cloudflare Workers, etc.

It seems to me that these services usually encapsulate infrastructure completely, and developers interact with these through high-level APIs such as HTTPS. And an architecture POV, they are themselves built from the lower-level compute and storage primitives that are not within the control of the developer. If we agree that there is no loss of security when using these services, then some approaches we might take could be:

1. Treating such CSP services identically to SaaS.
2. Make it clear that the section on network segmentation only applies to resources that require deployment into a VPC
3. Provide concrete examples of what the policy applies to, and what it does not for ease of interpretability
4. Recommend some approaches that improve the security of the network posture (e.g. VPC Endpoints for DynamoDB)

2022-05-20 07:04 UTC, hunter commented on networking.md
> +Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
I'd be leaning towards a mandate for limiting egress since it can mitigate a significant number of risks if an application is compromised. I think in the scope of the sandbox with using only managed services then it might be possible to recommend until we find a usable.

> Is it a reasonable expectation for a dev team to have to find out all the domain and IP addresses that a SaaS provider uses though, especially if the information may not have been published?

I do think it is reason to expect developers to know how their app is communicating. Even without considering security, knowing where an App needs to make external network requests can help with debugging and reliable operations (eg. Twilio is message delivery is slow and no reported outage, lets test the endpoint)

On application architecture specifics...

IPs are not a great means of egress access control since they can change and these days not a contiguous range for simple management but it is pretty easy to implement. Some services do publish (or discoverable from network logs) and it might be useful for the basics.

Glad to see that the IaC templates are including Network Firewall which should help simplify implementation. @ronghwa80 I'm looking forward to the team [innersourcing](https://www.developer.tech.gov.sg/guidelines/standards-and-best-practices/innersource.html) it 😉

Route53 DNS resolver firewalling is another alternative to add another layer of defence. Somewhat in-between a IP and a full URL firewall.

As something to sidestep the direct network egress (and related to the [comment](https://github.com/opengovsg/im8-cfa-sandbox/pull/4#issuecomment-1131806446) on CSP services), using an indirect method might be an alternative. eg. SNS topics triggering a Lambda to post to Twilio, streaming CW logs to Datadog via Kinesis, etc.

A few things to consider to add more flexibility (but also not something we want to encode in the guide... otherwise we end up like AIAS ;)

2022-05-23 02:52 UTC, liangyuanruo requested changes
> Outgoing Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity

Experiments on GCC 2.0 show that mandating the walled garden approach as worded currently could be extremely difficult to comply with, as it affects cloud infrastructure that the developer is not directly managing e.g. deployment health checks on Elastic Beanstalk.

2022-05-23 05:13 UTC, ronghwa80 requested changes
Thanks @hunter for the changes.

A recommendation for consideration. For line #7, the modal verb "must" can be seen as too restrictive for sandbox. This is assuming that the entry to join the sandbox is accurately assessed. I think we can nuance it to become "should" instead? Suppose if out going Internet access is not blocked by default, we may want this to be documented. Suppose if the system become mainstreamed, we can be more aware that this gap may need to be closed.

2022-05-23 06:14 UTC, hunter commented on networking.md
> +Outgoing Internet access **must** be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelis
Change to 'should' based on discussions

```suggestion
Outgoing Internet access should be blocked by default, with granular whitelisting for individual services that require Internet connectivity (e.g. through a network firewall with URL or IP whitelist)
```

2022-05-23 09:11 UTC, hunter commented
For the sake of expediency, lets merge and I'll raise a issue or PR for further discussing cloud-native/VPC-less services

2022-05-23 10:42 UTC, liangyuanruo approved these changes

2022-05-23 10:43 UTC, merged